# version: '3.8'

services:
  postgres-keycloak:
    image: postgres:16.8
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: ${POSTGRES_KEYCLOAK_DB}
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PW}
    volumes:
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - pgdata-keycloak:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_KEYCLOAK_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_KEYCLOAK_USER\"  -d \"$POSTGRES_KEYCLOAK_DB\""]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-app:
    image: postgres:16.8
    container_name: postgres-app
    environment:
      POSTGRES_DB: ${POSTGRES_APP_DB}
      POSTGRES_USER: ${POSTGRES_APP_USER}
      POSTGRES_PASSWORD: ${POSTGRES_APP_PW}
    volumes:
      - pgdata-app:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_APP_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_APP_USER\" -d \"$POSTGRES_APP_DB\""]
      interval: 5s
      timeout: 5s
      retries: 5

# define named volumes
volumes:
  pgdata-keycloak:
  pgdata-app: